version: '3.8'

services:

  postgres:
    image: postgres:14.2
    ports:
      - 5438:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker-postgres
    networks:
      - turbo-boilerplate

  maildev:
    image: maildev/maildev
    ports:
      - '1025:1025'
      - '1080:1080'
    networks:
      - turbo-boilerplate

networks:
  turbo-boilerplate:
